### ISSUE TITLE
Make pages light on dark for consistency

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#46]
> Moving onto the about lans page, my first thought is argh, why does the page design change?
> 
> Where did the big gray background go?
> 
> Either remove that entirely from the main page or use it to help emphasize the transitions between sections - I prefer the latter as i like that extra contrast.
> 
> Again font sizes are inconsistent.
>

**Comment by boardfish** [comment]
I'll look at moving both pages to light on dark.

**Comment by Aterfax** [comment]
Might want to add a separate issue for font size consistency?

**Comment by boardfish** [comment]
Also raising a separate issue for sass compilation - for some reason the result on the server is different than when run locally.

**Comment by boardfish** [comment]
Font size is a non-issue, it's standard everywhere.

**Comment by guruthree** [comment]
Is it just my eyes? The text size under the two section headings look different to me:
![b](https://user-images.githubusercontent.com/3973507/45265825-14d64880-b449-11e8-9dbb-bef77c3f6fdb.png)
![a](https://user-images.githubusercontent.com/3973507/45265826-156edf00-b449-11e8-8192-0590e40f0aff.png)
It looks like it only happens when there's no grey background, is the font size supposed to be bigger then?
